version: '3.4'

services:
  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: PaymentGateway.Api/Dockerfile
    ports:
      - "5000:5000"
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "test_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes: 
  sqlvolume: