version: '3.4'

services:
  paymentgateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  acquiringbank.mock:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

