// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentGateway.Data;

namespace PaymentGateway.Data.Migrations
{
    [DbContext(typeof(PaymentGatewayContext))]
    partial class PaymentGatewayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentGateway.Data.Entities.CardDetails", b =>
                {
                    b.Property<Guid>("CardDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardholderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardDetailsId");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("PaymentGateway.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CardDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyIsoAlpha3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CardDetailsId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PaymentGateway.Data.Entities.PaymentStatus", b =>
                {
                    b.Property<Guid>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StatusDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StatusKey")
                        .HasColumnType("int");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("PaymentGateway.Data.Entities.Payment", b =>
                {
                    b.HasOne("PaymentGateway.Data.Entities.CardDetails", "CardDetails")
                        .WithMany()
                        .HasForeignKey("CardDetailsId");
                });

            modelBuilder.Entity("PaymentGateway.Data.Entities.PaymentStatus", b =>
                {
                    b.HasOne("PaymentGateway.Data.Entities.Payment", null)
                        .WithMany("PaymentStatuses")
                        .HasForeignKey("PaymentId");
                });
#pragma warning restore 612, 618
        }
    }
}
